### ISSUE TITLE
Passing a css classes

### ISSUE THREAD

**Issue by sag1v** [fakiolinho/react-loading#17]
Hi, great and simple to use component!
I would like to suggest 2 features:
1. Add an optional prop for passing css classes/
2.  Add an optional prop for displaying the loader as overlay.

**Comment by fakiolinho** [comment]
No 1 was added in #27. For No 2 @sag1v you are talking about full-page overlay?

**Comment by sag1v** [comment]
@fakiolinho i forgot what i meant :man_facepalming: 
I think  meant an overlay as in blocking loader that blocks click events (could be full screen) not sure though. you can close this issue man. thanks

**Comment by fakiolinho** [comment]
@sag1v great thanks. I am closing this then :-)
