### ISSUE TITLE
Needs a maintainer

### ISSUE THREAD

**Issue by cezary** [fakiolinho/react-loading#26]
Hello,

Unfortunately I haven't had the time to maintain this project. Rather than let it stagnate and potentially break projects I'd be more than happy to transfer github and npm ownership over to anyone interested.

**Comment by fakiolinho** [comment]
Sure no worries!!! I am interested in helping here :-)

**Comment by cezary** [comment]
Hmm... getting an error when I try to transfer it, looks like it's conflicting with your fork of the react-loading:

![image](https://cloud.githubusercontent.com/assets/370808/25760539/0fe6a5e0-318c-11e7-8d84-18f3c923955c.png)

**Comment by fakiolinho** [comment]
I removed it. Can you please retry?

**Comment by fakiolinho** [comment]
Ok, it seems we are good @cezary Thanks!!!!!

**Comment by cezary** [comment]
Nice, set you up as the npm package owner so you can publish any changes. Thanks and good luck!

**Comment by fakiolinho** [comment]
Awesome, thanks again!!!
