### ISSUE TITLE
delay in loading

### ISSUE THREAD

**Issue by crobinson42** [fakiolinho/react-loading#30]
Our team is using `react-loading` in several sites and I notice there's an approx. delay of ~300ms before the loading icon renders. I've tried some simple surface debugging but no luck :-(

any help is appreciated.

**Comment by fakiolinho** [comment]
Hmmm, so `delay` prop is set to `0` and you can still notice some delay of ~300ms ?

**Comment by crobinson42** [comment]
Ahh - I'm sorry I didn't know there was a prop for delay. Out of curiosity, why us `delay` not set to 0 by default?
