### ISSUE TITLE
no default export

### ISSUE THREAD

**Issue by olleicua** [fakiolinho/react-loading#35]
As per the Readme I add the following to the top of my component:
```
import ReactLoading from 'react-loading';
```

I'm getting the following compile error when I try to import.
```
Module '"/Users/sauciello/work/project-ultron/node_modules/react-loading/index"' has no default export
```

**Comment by fakiolinho** [comment]
@olleicua could you please confirm that v1.0.3 has resolved this issue for you?

**Comment by fakiolinho** [comment]
Hmm, ok. Thanks
