### ISSUE TITLE
Default delay should be changed to 0

### ISSUE THREAD

**Issue by YoavHortman** [fakiolinho/react-loading#37]
I had a short load that I wanted to show to the client no matter how long it takes and the default delay was too long for it to show. I had to go back to the docs and try to understand why and after searching a bit I found the default delay is set to 1000ms.
Why isn't it set to 0 by default?

**Comment by Anandks1993** [comment]
Anyhow we can give can change delay through props right ?

**Comment by fakiolinho** [comment]
Yes exactly @Anandks1993 😀

**Comment by YoavHortman** [comment]
The point is this is not the expected behaviour and causes confusing outcomes in something that should be simple.

**Comment by Antman261** [comment]
Yes. This is very counterintuitive and easy to forget about. It has bitten us in the ass more than once. In fact right now I'm updating a dependency in a monorepo that uses react loading and will cause a cascade of updated packages with new dependencies. 

Why? Because I have to set delay to 0.

**Comment by fakiolinho** [comment]
Hmm, sad to hear that the behaviour of `delay` causes all this frustration. I agree this is not that straightforward i mean it is not expected to function like that by The truth is that some guys asked this feature sometime ago. Anyways, I am thinking to update this in 2.0 version

**Comment by fakiolinho** [comment]
Default value is set to 0 in newly released version `2.0.0` so you don't have blocking conflicts with this 😉
