### ISSUE TITLE
TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by Sunil-tc** [fakiolinho/react-loading#38]
I'm getting below error.
I'm using,
"react": "^16.2.0",
"react-loading": "^1.0.3",

TypeError: Cannot read property 'string' of undefined
(anonymous function)
node_modules/react-loading/dist/react-loading.js:138

exports['default'] = Loading;

Loading.propTypes = {
    color: _react.PropTypes.string,
    delay: _react.PropTypes.number,
    height: _react.PropTypes.oneOfType([_react.PropTypes.number, _react.PropTypes.string]),
    type: _react.PropTypes.string,

**Comment by fakiolinho** [comment]
@Sunil-tc i cannot replicate the issue please have a look [here](https://codesandbox.io/s/0op10wwowv)

**Comment by fakiolinho** [comment]
Now that `width` and `height` props are set explicitly to be numbers i think this issue is not valid anymore @Sunil-tc
