### ISSUE TITLE
Seems to be causing problems with webpack currently

### ISSUE THREAD

**Issue by richtera** [fakiolinho/react-loading#41]
For some reason this module includes the "process" shim which causes DefinePlugin to be unable to  replace process.env.NODE_ENV in any module included after this one.
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/206

**Comment by richtera** [comment]
Added pull request https://github.com/fakiolinho/react-loading/pull/42

**Comment by fakiolinho** [comment]
@richtera please let me know if your problem is resolved in v1.0.4

**Comment by fakiolinho** [comment]
No need to ask sorry 😉 thanks @richtera
