### ISSUE TITLE
Example in docs seems wrong

### ISSUE THREAD

**Issue by patrickptm** [fakiolinho/react-loading#46]
1. The example presents using props like this:

`<ReactLoading type={type} color={color} height='667' width='375' />`
However not specifying px in height and width results in a weird behaviour (it's either not working or it occupies the entire page.
This seems to be the correct way:
`<ReactLoading height='25px' width='25px' />`

2. This also applies to "delay" props:
`<ReactLoading delay="10ms" />` - the way to make it work, but still throws a warning.
`<ReactLoading delay="10" />` - throws a warning.

the warning is:
![warningmessage](https://user-images.githubusercontent.com/20436002/37908286-aefd8c34-30ff-11e8-97f0-40a6afc2fa78.PNG)

**Comment by fakiolinho** [comment]
Hmm you are definitely right @patrickdronk

**Comment by fakiolinho** [comment]
Ok 1 is fixed so only numbers are expected and 2 is normal since only numbers are expected for delay too. Closing this thanks again 👋
