### ISSUE TITLE
Delay Default Value

### ISSUE THREAD

**Issue by Samuel-Montoya** [fakiolinho/react-loading#47]
Just out of curiosity and feedback, should the delay parameter have a default value already? I don't know about anyone else, but I like having the loading show up as soon as it's rendered.

Should this be changed to a default value of zero?

Hopefully this feedback is helpful!

**Comment by fakiolinho** [comment]
Yeah @Samuel-Montoya you are definitely right. I plan to make this optional in version 2. Closing this because of #37
