### ISSUE TITLE
could you remove sourceMappingURL from react-loading.js

### ISSUE THREAD

**Issue by zhangolve** [fakiolinho/react-loading#55]
I find When I use webpack to build my app,the part of react-loading module was too big. the reason was that you encode sourceMappingURL as base64 (/*#sourceMappingURL=data:application/json;base64,eyJ2ZXJza */)
and put it as comment in the react-loading.js .

I use UglifyJsPlugin to compress my bundle and use its default config.

```
            new UglifyJsPlugin({
                cache: true,
                parallel: true,
                sourceMap: true
            })
```
When I use the config to build my app, the compressed react-loading module size is 101k.
When I remove the comments(above 100k), the compressed react-loading module size is  44k.

**Comment by fakiolinho** [comment]
@zhangolve excellent idea. Are you willing to submit a pull request for this?
