### ISSUE TITLE
Things I would like to have

### ISSUE THREAD

**Issue by kof** [fakiolinho/react-loading#7]
- es6 support
- only loading svg I really use
- implementation of delay - only render indicator if component is still mounted after Xms, where recommended value is 1000.

**Comment by kof** [comment]
Would you accept or PR or willing implement them?

**Comment by cezary** [comment]
So I added the delay, I'm not sure what you mean by es6 support but it's using es6 classes to create the component and I fixed the broken dist file.

I'm not sure how I'd go about implementing selective svg loading, but I'd be happy to accept a PR.

**Comment by hifilorau** [comment]
for es6 you can just use: import Loading from 'react-loading'
