### ISSUE TITLE
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.

### ISSUE THREAD

**Issue by HillLiu** [fakiolinho/react-loading#8]
Alert by react.js

**Comment by mwkang** [comment]
I have a same message.

**Comment by davodesign84** [comment]
Same, any plan to fix that or alternative library to use?

**Comment by jch254** [comment]
Me too!

**Comment by mbeauchamp7** [comment]
Same same

**Comment by artemkaint** [comment]
+1

**Comment by jpmelnik** [comment]
And Me! +1

**Comment by cezary** [comment]
What browser and version are you using? I haven't seen a deprecation warning in a while and [it looks like they've suspended deprecating SMIL](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/5o0yiO440LM%5B126-150%5D).

**Comment by mcmxc** [comment]
same warning I got

**Comment by JeremyWuuuuu** [comment]
+1 , XD , btw , how can I change the loading bar's position?

**Comment by HillLiu** [comment]
close outdated issue.
