### ISSUE TITLE
spinning-bubbles broken

### ISSUE THREAD

**Issue by AndrewBestbier** [fakiolinho/react-loading#9]
Hi there,

Thank you for your great library! I could get all the other loaders to work except for the spinning-bubbles one. Does anyone else experience this?

**Comment by booxood** [comment]
me too...

**Comment by booxood** [comment]
I resolved it. see https://github.com/cezary/react-loading/blob/master/lib%2Fsvg%2Findex.js#L8.

spinning-bubbles -> spinningBubbles
```
<Loading type='spinningBubbles' color='#333' />
```
